[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]
resolver = "2"

[workspace.dependencies]
hdi = "=0.6.3"
hdk = "=0.5.3"
holochain_serialized_bytes = "*"
serde = "1.0"

[workspace.dependencies.nondominium]
path = "dnas/nondominium/zomes/coordinator/nondominium"

[workspace.dependencies.nondominium_integrity]
path = "dnas/nondominium/zomes/integrity/nondominium"
