name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-ci
          skipPush: true

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target
            vendor/hrea -> vendor/hrea/target

      - name: Install dependencies
        run: nix develop --command bun install

      - name: Build happ
        run: nix develop --command bun run build:happ

      - name: Run tests
        run: nix develop --command bun run test:only
